name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ou a branch que você está usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (caso você use Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Ajuste conforme sua versão do Node.js

      - name: Install dependencies
        run: |
          npm install  # Ou o comando que você usa para instalar dependências

      - name: Build static content (se necessário)
        run: |
          npm run build  # Ajuste esse comando se precisar compilar algo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Ou o diretório onde está o arquivo final (HTML, CSS)
